### ISSUE TITLE
sim_learn doesn't output 'live'

### ISSUE THREAD

**Issue by nils-wisiol** [nils-wisiol/pypuf#80]
When running sim_learn with a large number of experiments (e.g., `sim_learn.py 32 4 lightweight_secure_original xor 12000 100 1 0xabc 0x1`), no output is generated until all experiments are finished.

**Comment by MrM0nkey** [comment]
Yes this happends because the experimenter is silent a the moment. You cloud poll the logfile or we add an stream handler to https://github.com/nils-wisiol/pypuf/blob/master/pypuf/experiments/experimenter.py#L86-L93 as hotfix.
For example:
```
def setup_logger(logger_name):
    root = logging.getLogger(logger_name)

    # Setup logging to both file and console
    file_handler = logging.FileHandler(filename='%s.log' % logger_name, mode='w')
    file_handler.setLevel(logging.INFO)

    stream_handler = logging.StreamHandler(sys.stdout)
    stream_handler.setLevel(logging.INFO)

    root.addHandler(file_handler)
    root.addHandler(stream_handler)
```
In order to prevent double print the results the [lines](https://github.com/nils-wisiol/pypuf/blob/master/sim_learn.py#L135-L143) should be deleted. In my opinion it is not necessary to print the results live because the terminal gets overpowered with output. I hope this hotfix is enough for you. I do not want to enable the output by default. Hence it would be necessary to implement a option for verbose behavior.
